# -*- coding: utf-8 -*-
"""Lógica 01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zmgMCfqZ00NvtYSi1C-WXuFys6SUZw25

Primeira aula de lógica
"""

variavel = 56
variavel2 = 76


soma = variavel + variavel2
print(soma)

"""Exercício 1 - Lógica de programação (desconto no transporte público)"""

valor_passagem = 4.5
desconto = 50
estudante = input(" Se você é estudante, digite 1: ")
pcd = input(" Se você é pcd, digite 1: ")

if (estudante or pcd):
  total = valor_passagem * (desconto/100)
else:
  total = valor_passagem

print (f"O valor da sua passagem é: {total}")

"""Exercício 2 - Lógica de programação (algoritmo para calcular as unidades de uma sequencia de números)"""

inicio = input("digite o número inicial: ")
final = input("digite o número final: ")
lista=[]
total=1

for i in range(int(inicio),int(final)+1):
  if i%2 != 0:
    lista.append(i)

for j in lista:
  total = total * j

print(f" a lista é : {lista}")
print(f" o valor total da multiplicação é {total}")

"""Exercício 3 - Controle de Acesso a um Evento"""

def verificar_acesso(idade, acompanhado):
    if idade >= 18 or (idade < 18 and acompanhado):
        return "Acesso permitido"
    else:
        return "Acesso negado"

idade = int(input("Digite a idade: "))
acompanhado_input = input("Está acompanhado de um responsável? (sim/não): ").strip().lower()
acompanhado = acompanhado_input == "sim"

resultado = verificar_acesso(idade, acompanhado)
print(resultado)

"""Exercício 4 - Supermercado"""

def caixa_supermercado():
    total = 0.0
    print("Digite o preço dos produtos (digite 0 para finalizar a compra):")

    while True:
        try:
            preco = float(input("Preço do produto: R$ "))
            if preco < 0:
                print("Preço inválido. Digite um valor positivo ou 0 para encerrar.")
                continue
            if preco == 0:
                break
            total += preco
        except ValueError:
            print("Entrada inválida. Digite um número.")

    print(f"\nTotal da compra: R$ {total:.2f}")

    pagamento = input("Forma de pagamento (dinheiro/cartão): ").strip().lower()

    if pagamento == "dinheiro":
        desconto = total * 0.10
        total_final = total - desconto
        print(f"Desconto de 10% aplicado: R$ {desconto:.2f}")
    else:
        total_final = total
        print("Sem desconto aplicado.")

    print(f"Valor final a pagar: R$ {total_final:.2f}")

caixa_supermercado()

