# -*- coding: utf-8 -*-
"""Lógica 02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Em_ghF9SFW63zo0kHuZqIFX-QiTXpt1s

Criando funções
"""

def soma(x,y):

    if type(x) == type(y):
        soma = x + y
        print(soma)
        return soma
    else:
        print("tipos de dados diferentes")

soma("a", 4)

"""Sequência de Fibonacci
F(n) = F(n1) + F(n2) -> F1 = 1 e F2 = 1

"""

def fibonacci_otimizado(n):
    a, b = 0, 1
    for _ in range(n):
        print(a, end=" ")
        a, b = b, a + b
fibonacci_otimizado(10)

def fibonacci(n):
    if n <= 1:
        return n
    else:
        return fibonacci(n - 1) + fibonacci(n - 2)

for i in range(10):
    print(fibonacci(i), end=" ")

